name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Configure Git to use UTF-8
        run: |
          git config --global i18n.commitEncoding utf-8
          git config --global i18n.logOutputEncoding utf-8

      - name: Clone Hugging Face Repo into current directory
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          rm -rf .git
          git init
          git remote add origin https://user:$HF_TOKEN@huggingface.co/spaces/itsbhavesh123/Math_Solver
          git fetch origin main || echo "No remote branch yet"
          git reset --hard origin/main || echo "Nothing to reset"
          git rm -rf . || true
          rm -rf * .[^.]* || true
          git clean -fdx || true

      - name: Copy GitHub Repo Files to current directory
        run: |
          rsync -av --delete --exclude='.git' --exclude='.github' ./ ../temp_copy/ || [[ $? == 24 ]]
          rm -rf * .[^.]* || true
          rsync -av ../temp_copy/ ./ || [[ $? == 24 ]]

      - name: Commit & Push to Hugging Face (Clean State)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git add .
          git commit -m "✨ Clean deploy from GitHub Actions" || echo "Nothing to commit"
          git branch -M main
          git push -f https://user:$HF_TOKEN@huggingface.co/spaces/itsbhavesh123/Math_Solver main
