name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "you@example.com"

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/itsbhavesh123/Math_Solver hf_space
          rsync -av --delete --exclude='.git' ./ hf_space/
          cd hf_space
          git add .
          git commit -m "🚀 Sync from GitHub Actions" || echo "Nothing to commit"
          git push https://itsbhavesh123:$HF_TOKEN@huggingface.co/spaces/itsbhavesh123/Math_Solver main
