name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/itsbhavesh123/Math_Solver hf_space
          
          # rsync with --delete but ignore exit code 24 (vanishing files)
          rsync -av --delete --exclude='.git' .|| [[ $? == 24 ]]

          git add .
          git commit -m "🚀 Auto Deploy from GitHub Actions" || echo "Nothing to commit"
          git push https://user:$HF_TOKEN@huggingface.co/spaces/itsbhavesh123/Math_Solver main
