name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git to use UTF-8
        run: |
          git config --global i18n.commitEncoding utf-8
          git config --global i18n.logOutputEncoding utf-8

      - name: Clone Hugging Face Space Repo
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://user:$HF_TOKEN@huggingface.co/spaces/itsbhavesh123/Math_Solver .
      
      - name: Copy Files and Push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          rsync -av --delete --exclude='.git' --exclude='.github' ../ ./ || [[ $? == 24 ]]
          git add .
          git commit -m "🚀 Auto Deploy from GitHub Actions" || echo "Nothing to commit"
          git push https://user:$HF_TOKEN@huggingface.co/spaces/itsbhavesh123/Math_Solver main
